version: '3.8'
services:
    mongo:
        image: mongo
        container_name: mongo
        network_mode: 'host'
        environment: 
            - PUID=1000
            - PGID=1000
        volumes:
            - ./db:/data/db
        restart: unless-stopped

    backend:
        build: backend/.
        container_name: backend
        command: python3 /app/backend/src/app.py
        network_mode: 'host'
        environment:
            - PUID=1000
            - PGID=1000
        # volumes:
        #     - ./app:/app
        restart: unless-stopped